significa/significa.co

content/pages/about/about.yml

- Add Pedro Lisboa as team member in About page
There was no Pedro Lisboa at it

Team members update

---

content/pages/about/about.yml
src/components/About/Team/index.tsx

- Add Cleyson to team list
- Remove Danilo to team list
- Order team member by alphabet
Using `localeCompare`, this feature has a good compatibility, see on [can i use](https://caniuse.com/?search=localeCompare)

feat(about page): change team list and order team name by alphabet

---

src/components/seo.svelte

- Fixes SEO component behaviour when using it without props, which lead to direct reading of $page store with the wrong fields, returning `undefined` every time.
Closes SIGN-504

[SEO] Wrong $page store values

---

src/components/physics-section.svelte

Fixed physics side effect `$:` running unexpectedly
before:
https://github.com/significa/significa.co/assets/98809371/1eda5cbf-c5d6-48de-b213-36d5b67e5ede
after:
https://github.com/significa/significa.co/assets/98809371/5aa10990-97cd-428d-ba34-35037eb70440

Physics section side effect after resizing SIGN-442 SIGN-433

---

src/lib/drawings.server.ts

Kind of a hack: a boolean that is a string 😅 
But we will hopefully migrate away from Dynamo very soon.

Add is_deleted to seggs drawing store

---

src/components/pages/blog-post.svelte

fix: decrease post get a quote margins [SIGN-543]

---

src/components/pages/services.svelte

Decreased space between project name and award
**Before**
**After**

fix: decrease margin in awards mobile version

---

src/components/pages/home/services.svelte

The bug occurred only on a mobile view and instead of using the physics engine we are using static images on mobile. The problem was that we were hiding the DOM element but the component logic would still run. Since we use the two different approaches because of the interferences on drag, drop and scroll, I used the verification to confirm if the device was touch or point to solve the issue.
Thanks @filipeff95 for the help :)

fix: Newton component in mobile [SIGN-562]

---

src/components/blocks/comparison.svelte

https://linear.app/significa/issue/SIGN-561/the-slider-image-component-does-not-work-on-mobile

fix: image comparison mobile events

---

src/lib/utils/paths.ts

https://linear.app/significa/issue/SIGN-517/%5Bhandbook%5D-the-url-is-not-synced-with-the-chapter-title-it-has-an

fix: slugify helper to remove html tags from string

---

src/components/pages/home/home-about.svelte

https://linear.app/significa/issue/SIGN-525/[mobile-qa]-[home-page]-decrease-the-space-between-description-and

fix: margin between button and text

---

src/components/clock.svelte

https://linear.app/significa/issue/SIGN-389/refresh-clock-on-page-focus

fix: refresh clock on page focus

---

src/components/pages/blog-post.svelte
src/lib/i18n/data.json
src/lib/i18n/types.ts

https://linear.app/significa/issue/SIGN-544/[mobile-qa]-[blog]-i-miss-a-title-after-the-yellow-card-to-give-some

feat: blog pre footer related articles title

---

src/components/blog-entry.svelte
src/components/pages/blog-post.svelte
src/components/person.svelte

Fixes SIGN-584
- Add (former) to person component
- Pass is_active to person as prop in blog-entry
- Pass is_active to person as prop in blog-post

fix: tag former team members as such in blog

---

src/components/footer.svelte

Fixes SIGN-610
We had a block level element as a child of an inline level element which was causing issues with rendering on safari.
With this change we lose visibility on why that div was there in the first place since it stops being the commit being shown in the git blame. It is an hack to avoid it being shown in the google results page listing. It is specified on the issue SIGN-564. Leaving it here as documentation if someone comes searching for answers in the future

fix: correct footer careers badge position in safari

---

components.198185.json
presets.198185.json
src/components/blog-entry.svelte
src/components/pages/blog-post.svelte
src/components/person.svelte
src/lib/content.ts
src/lib/utils/cms.ts
src/types/bloks.d.ts

feat: allow multiple authors

---

src/components/proposals/proposal-timeline.svelte

Quick change to allow rate proposals' timeline to be displayed in weeks rather than months.
Can be improved in the future to avoid the code duplication and have a flag where the user chooses the unit in which the timeline should be displayed

feat: change rate proposal timeline to display weeks

---

src/components/pages/handbook-page.svelte

Because of the missing "/" the links were being treated as relative paths, which caused a bug when the user was linking from an handbook page turning the links into "/handbook/handbook/<slug>"

fix: fix issue with handbook drawer links

---

src/components/seo.svelte

- Adds canonical url (as the default page url)  to SEO and add `seo_canonical_url` field to overwrite it;
- This changes apply to `page`, `blog-post` and `landing-page`;
To test you can add the `seo_canonical_url` on the `SEO` tab and see within the `<head>` tag a `link` with `rel="canonical"` like `<link rel="canonical" href="https://localhost:5173/blog/comet-chat-test">`;

SEO > Add `seo_canonical_url` field for `Page` | `Landing Page` and `Blog Post`

---

components.198185.json
src/components/footer.svelte
src/types/bloks.d.ts

feat(footer): client logo

---

src/lib/actions/drawer-links.ts

This happens because the drawer search parameter sometimes includes a duplicated parent folder (e.g., /careers/careers/internship-marketing-designer instead of /careers/internship-marketing-designer), leading to a 404 error. 
To resolve this, I use the link’s href value, which ensures that the drawer always contains the correct story path.
https://github.com/user-attachments/assets/1c029db7-b92f-4593-8f9b-a93ccbc1356b

[BUG Fix] Page Drawer > Sometimes the page is empty

---

src/components/page-drawer.svelte
src/lib/stores/drawer.ts

- Make the page drawer header sticky to enhance navigation and UX

Page Drawer > Make  the header sticky
