significa/significa.co

src/components/Careers/FormPosition/styled.tsx, src/components/Contact/Form/styled.ts, src/components/UI/Forms/common.ts
=> fix(forms):

src/components/Projects/Section/sections/Gallery/index.tsx, src/components/Projects/Section/sections/Sticky/index.tsx, src/components/Projects/Section/sections/Video/index.tsx
=> fix(autoplay): adds autoplay to ios

content/projects/opennode.yml, src/components/Projects/Chapter/index.tsx, src/components/Projects/Chapter/styled.ts, src/components/Projects/Section/styled.ts, src/templates/project.tsx
=> Chapter margin

content/footer.yml, content/menu.yml, gatsby-node.js
=> Redirects and menu

src/components/UI/ContentThumb/styled.tsx
=> fix(ff): fix blur images performance on firefox

.eslintrc.json, modules.d.ts, src/components/Blog/AuthorBox/AuthorBox.tsx, src/components/Blog/AuthorBox/styled.ts, src/components/Blog/AuthorSection/AuthorSection.tsx, src/components/Blog/AuthorSection/styled.ts, src/components/Handbook/Cover/index.tsx, src/components/Handbook/Cover/styled.ts, src/components/PrismicImage/index.tsx, src/components/Projects/Hero/index.tsx, src/components/Projects/Hero/styled.tsx, src/components/Projects/Section/sections/Comparison/index.tsx, src/components/Projects/Section/sections/Gallery/index.tsx, src/components/Projects/Section/sections/Image/index.tsx, src/components/Projects/Section/sections/Slideshow/index.tsx, src/components/Projects/Section/sections/Sticky/index.tsx, src/components/Projects/Section/sections/Waterfall/index.tsx, src/components/Projects/Section/types.ts, src/pages/preview.tsx, src/templates/blog-post.tsx, src/templates/handbook.tsx, src/templates/position.tsx, src/templates/project.tsx, src/templates/project.types.ts
=> Prismic preview

content/pages/about/about.yml
This commit updates the list of members Significa.co team.
=> feat(members of team): update members of the team in About page

content/pages/about/about.yml
=> feat(add-developer): add developer to about.yml

content/pages/contact/contact.yml, src/components/Careers/FormPosition/index.tsx, src/components/Contact/Form/index.tsx
- Updates copy
- Changes Form Position Background theme
=> Careers update

schemas/blog_post.json, src/components/Blog/types.ts, src/pages/blog.tsx
- Adds blog page listed feature to all blog posts
=> Blog Post Listed

src/components/contact-form.svelte, src/components/hoverable-gallery-card.svelte, src/components/illustrations/stickers/bird.svelte, src/components/images.svelte, src/components/pages/get-a-quote/form.svelte, src/components/pages/handbook.svelte, src/components/split-lines.svelte, src/components/top-navigation.svelte, tailwind.config.cjs
Closes SIGN-483 SIGN-484 SIGN-477 SIGN-463
=> [Bug fixing] 15/05/23

components.198185.json, src/components/pages/team-member.svelte, src/types/bloks.d.ts
=> [Pages] [Author] Cover illustration

src/components/seo.svelte
=> [SEO] fix OG image SIGN-504

src/components/hoverable-gallery-card.svelte, src/components/pages/careers/canvas.svelte, src/components/top-navigation.svelte, src/routes/handbook/[...path]/+layout.svelte
- update minimap style
- topbar bottom border
- hoverable contact cards
=> misc. fixes

src/routes/healthz/+server.ts
Adds health route in `/healthz`.
Also adds guide to the development standards https://www.notion.so/significa/75156aa885914203b1938b4911e5ebff
=> feat: add health route

src/components/contact-form.svelte, src/components/pages/home/services.svelte
=> fix: increase space in contacts [SIGN-549]

src/routes/+error.svelte
=> fix: 404 page title [SIGN-552]

components.198185.json, presets.198185.json, src/lib/i18n/data.json, src/lib/i18n/types.ts, src/routes/(proposals)/proposal/[slug]/+page.server.ts, src/routes/(proposals)/proposal/[slug]/+page.svelte, src/routes/(proposals)/proposal/[slug]/password-form.svelte, src/routes/(proposals)/proposal/[slug]/password-input.svelte, src/types/bloks.d.ts
=> feat: add components passwordform [SIGN-582]

src/components/blocks/rich-text-testimonial.svelte
https://linear.app/significa/issue/SIGN-542/[mobile-qa]-[blog]-add-more-pace-between-quote-and-the-remaining
=> fix: more space on testimonial mobile

src/components/blocks/rich-text-testimonial.svelte, src/components/pages/about.svelte, src/components/pages/blog-post.svelte, src/components/pages/careers.svelte, src/components/pages/services.svelte, src/lib/i18n/data.json, src/lib/i18n/types.ts
https://linear.app/significa/issue/SIGN-536/[mobile-qa]-[services-page]-missing-dividers-between-services-topics
https://linear.app/significa/issue/SIGN-545/[mobile-qa]-[careers]-spontaneous-link-seems-almost-imperceptible-what
https://linear.app/significa/issue/SIGN-546/[mobile-qa]-[careers]-add-more-space-between-title-and-the-element
https://linear.app/significa/issue/SIGN-540/[mobile-qa]-[about-page]-decrease-the-title-font-size-clients-weve
https://linear.app/significa/issue/SIGN-537/[mobile-qa]-[services-page]-increase-the-title-and-description-font
https://linear.app/significa/issue/SIGN-542/[mobile-qa]-[blog]-add-more-pace-between-quote-and-the-remaining
https://linear.app/significa/issue/SIGN-544/[mobile-qa]-[blog]-i-miss-a-title-after-the-yellow-card-to-give-some
=> QA mobile fixes

src/components/gtag.svelte, src/routes/+layout.svelte
gtag and service page event snippet
=> feat: gtag

components.198185.json, src/routes/(proposals)/proposal/[slug]/+page.server.ts, src/routes/(proposals)/proposal/[slug]/hero.svelte, src/routes/(proposals)/proposal/[slug]/proposal-page.svelte, src/types/bloks.d.ts, vite.config.ts
https://github.com/significa/significa.co/assets/19336587/7b2139c1-2f9a-459a-b27d-b251faa85181
=> feat: add sections body [SIGN-570]

src/app.html
=> revert matomo tracking

src/components/pages/project.svelte
[Issue](https://linear.app/significa/issue/SIGN-598/awards-bug-mobile)
=> fix: spacing

src/components/proposals/proposal-package.svelte
=> feat: change package proposal popover data field

src/components/proposals/proposal-estimates.svelte, src/components/proposals/proposal-team.svelte
=> fix: remove dynamic tailwind variables

src/components/proposals/proposal-package.svelte, src/components/proposals/proposal-timeline.svelte, src/lib/utils/proposals.ts
=> feat: change days per month calculations in package proposals

src/components/blocks/estimation.svelte
https://linear.app/significa/issue/SIGN-616/blok-estimation-packages
=> fix: width

static/robots.txt
=> feat: add sitemap to robots.txt

src/components/handbook-navigation.svelte, src/components/page-drawer.svelte
=> fix: get handbook data from correct source in drawer

src/hooks.client.ts, src/hooks.server.ts
=> feat: remove sentry performance monitoring

src/components/contact-form.svelte
=> fix: issues with character limit for career form

scripts/sitemap.ts
=> fix: sitemap
